use std::path::Path;

use openagents_core::{ResolvedProfile, ToolKind};

pub fn render_adapter_output(
    tool: ToolKind,
    workspace_name: &str,
    profile: &ResolvedProfile,
) -> Result<String, AdapterError> {
    let mut guidance_packs = profile
        .tools
        .values()
        .flat_map(|config| config.guidance_packs.iter().cloned())
        .collect::<Vec<_>>();
    guidance_packs.sort();
    guidance_packs.dedup();
    let guidance = guidance_packs.join(", ");

    let rendered = match tool {
        ToolKind::Codex => format!(
            "# Generated by OpenAgents Kit for {workspace_name}\n# Merge this snippet into ~/.codex/config.toml\n# profile = {}\n# memory_provider = {}\n# memory_endpoint = {}\n# guidance = [{guidance}]\n# Inspect or seed the shared memory store with:\n#   openagents-kit memory --profile {} --format json --ensure\n# Replace <workspace-root> with the absolute path to the client workspace.\n[projects.'<workspace-root>']\ntrust_level = \"trusted\"\n\n# When your shared-memory bridge is ready, add it below.\n# [mcp_servers.openagents_memory]\n# command = \"openagents-kit\"\n# args = [\"memory\", \"--profile\", \"{}\", \"--format\", \"json\", \"--ensure\"]\n",
            profile.name,
            profile.memory.provider,
            profile.memory.endpoint,
            profile.name,
            profile.name
        ),
        ToolKind::Claude => format!(
            "# OpenAgents Kit\n\nProfile: `{}`\nWorkspace: `{workspace_name}`\nMemory provider: `{}`\nMemory endpoint: `{}`\nGuidance packs: `{guidance}`\nInspect or seed the shared memory store with `openagents-kit memory --profile {} --format json --ensure`.\nNext step: review the generated memory endpoint and merge any project-specific instructions before handing this to a client.\n",
            profile.name, profile.memory.provider, profile.memory.endpoint, profile.name
        ),
        ToolKind::Gemini => format!(
            "# GEMINI profile bootstrap\n\nprofile: {}\nworkspace: {workspace_name}\nmemory_provider: {}\nmemory_endpoint: {}\nguidance: {}\ninspect_memory: openagents-kit memory --profile {} --format json --ensure\nnext_step: review the generated memory endpoint and merge any project-specific instructions before handing this to a client.\n",
            profile.name, profile.memory.provider, profile.memory.endpoint, guidance, profile.name
        ),
    };

    Ok(rendered)
}

pub fn write_adapter_output(
    root: &Path,
    tool: ToolKind,
    rendered: &str,
) -> Result<(), AdapterError> {
    let tool_dir = root.join(tool.to_string());
    std::fs::create_dir_all(&tool_dir)?;
    std::fs::write(tool_dir.join(tool.file_name()), rendered)?;
    Ok(())
}

#[derive(Debug, thiserror::Error)]
pub enum AdapterError {
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
}

#[cfg(test)]
mod tests {
    use crate::render_adapter_output;
    use openagents_core::{ToolKind, WorkspaceManifest};

    #[test]
    fn renders_codex_output_with_memory_hint() {
        let fixture = include_str!("../../../examples/basic/workspace.yaml");
        let manifest = WorkspaceManifest::from_yaml_str(fixture).expect("manifest should parse");
        let profile = manifest
            .resolve_profile("personal-client")
            .expect("profile should resolve");

        let rendered = render_adapter_output(ToolKind::Codex, &manifest.workspace, &profile)
            .expect("codex output should render");

        assert!(rendered.contains("Merge this snippet into ~/.codex/config.toml"));
        assert!(rendered.contains("[projects.'<workspace-root>']"));
        assert!(rendered.contains("shared-memory"));
        assert!(rendered.contains("--format\", \"json\", \"--ensure"));
    }

    #[test]
    fn renders_claude_output_with_profile_context() {
        let fixture = include_str!("../../../examples/basic/workspace.yaml");
        let manifest = WorkspaceManifest::from_yaml_str(fixture).expect("manifest should parse");
        let profile = manifest
            .resolve_profile("company-team")
            .expect("profile should resolve");

        let rendered = render_adapter_output(ToolKind::Claude, &manifest.workspace, &profile)
            .expect("claude output should render");

        assert!(rendered.contains("company-team"));
        assert!(rendered.contains("team-handoff"));
        assert!(
            rendered
                .contains("openagents-kit memory --profile company-team --format json --ensure")
        );
    }
}
